import 'package:flutter/material.dart';
import 'package:book_bridge/features/reviews/domain/entities/review_entity.dart';
import 'package:book_bridge/features/reviews/domain/usecases/create_review_usecase.dart';
import 'package:book_bridge/features/reviews/domain/usecases/has_reviewed_usecase.dart';
import 'package:book_bridge/features/transactions/domain/usecases/get_transaction_by_external_ref_usecase.dart';
import 'package:book_bridge/features/transactions/domain/entities/transaction_entity.dart';
import 'package:dartz/dartz.dart';
import 'package:book_bridge/core/error/failures.dart';

enum ReviewState { idle, submitting, success, error }

class ReviewViewModel extends ChangeNotifier {
  final CreateReviewUseCase createReviewUseCase;
  final HasReviewedUseCase hasReviewedUseCase;
  final GetTransactionByExternalRefUseCase getTransactionByExternalRefUseCase;

  ReviewViewModel({
    required this.createReviewUseCase,
    required this.hasReviewedUseCase,
    required this.getTransactionByExternalRefUseCase,
  });

  ReviewState _state = ReviewState.idle;
  ReviewState get state => _state;

  String? _error;
  String? get error => _error;

  int _rating = 0;
  int get rating => _rating;

  void setRating(int rating) {
    _rating = rating;
    notifyListeners();
  }

  Future<bool> checkIfReviewed(String transactionId, String reviewerId) async {
    final result = await hasReviewedUseCase(transactionId, reviewerId);
    return result.fold((failure) => false, (hasReviewed) => hasReviewed);
  }

  Future<Either<Failure, TransactionEntity>> getTransactionByExternalRef(
    String externalRef,
  ) async {
    return await getTransactionByExternalRefUseCase(externalRef);
  }

  Future<void> submitReview({
    required String reviewerId,
    required String revieweeId,
    required String listingId,
    required String transactionId,
    String? comment,
  }) async {
    if (_rating == 0) {
      _error = 'Please provide a rating';
      notifyListeners();
      return;
    }

    _state = ReviewState.submitting;
    _error = null;
    notifyListeners();

    final review = ReviewEntity(
      id: '', // Will be generated by Supabase
      reviewerId: reviewerId,
      revieweeId: revieweeId,
      listingId: listingId,
      transactionId: transactionId,
      rating: _rating,
      comment: comment,
      createdAt: DateTime.now(),
    );

    final result = await createReviewUseCase(review);

    result.fold(
      (failure) {
        _state = ReviewState.error;
        _error = failure.message;
      },
      (_) {
        _state = ReviewState.success;
      },
    );

    notifyListeners();
  }

  void reset() {
    _state = ReviewState.idle;
    _error = null;
    _rating = 0;
    notifyListeners();
  }
}
